Feature/1240 map test dat from json file to java object
ShaftHQ/SHAFT_ENGINE pull request #1241
Opened 2023-08-21 06:34 UTC by MamdouhMansour

2023-08-21 06:36 UTC, MamdouhMansour commented
Related to #1240

2023-08-21 07:45 UTC, MohabMohie commented on src/main/java/objectclass/BodyObject.java
Question...
Is it possible to build this class dynamically in run time after parsing the json file?
@MhmdElGazzar supervised a similar implementation with the CuRL to POJO generator, is it possible to create a dynamic json to POJO parser? better-yet, did someone already do this and can we just use it as a dependency?

To me, it makes little sense having a static mapping with static json property names for test data... we have a similar static implementation for SHAFT properties, but for test data I think we need a dynamic implementation.


aside from that, this looks like an excellent implementation. Thanks Mamdouh.

2023-08-21 07:47 UTC, MohabMohie requested changes
one minor change request, can we move the BodyObject.java to the src/test/java directory since it's not a part of the engine (because it has static mapping of the specific test data we're using to test this feature).

2023-08-21 14:09 UTC, MamdouhMansour commented on src/main/java/objectclass/BodyObject.java
@MhmdElGazzar @MohabMohie would like to know more to implement

2023-08-21 14:14 UTC, MamdouhMansour commented
@MohabMohie moved pojo out of the engine

2023-08-22 14:51 UTC, MamdouhMansour commented
@MohabMohie what we need to complete this PR?

2023-08-23 13:17 UTC, MohabMohie approved these changes

2023-08-23 13:17 UTC, merged