fix allure history and trends generation
ShaftHQ/SHAFT_ENGINE pull request #1800
Opened 2024-11-08 22:59 UTC by MohabMohie

-allure.accumulateHistory=true
will now behave as expected, saving execution history and showing relevant trends to help identify flaky tests.

-allure.accumulateReports=true
will now be more relevant, as the report will hold details of the current test run only; previous run details will no longer show in the retries tab.

2024-11-09 09:17 UTC, AhmdZanoon requested changes

2024-11-09 09:17 UTC, AhmdZanoon commented on src/main/java/com/shaft/tools/io/internal/AllureManager.java
> +            internalTerminalSession.performTerminalCommand(getCommandToCreateAllureReport(customReportName, false));
Dear @MohabMohie , I think this line will cancel the previous one , so the report will always be without history .

2024-11-09 09:21 UTC, MohabMohie commented on src/main/java/com/shaft/tools/io/internal/AllureManager.java
> +            internalTerminalSession.performTerminalCommand(getCommandToCreateAllureReport(customReportName, false));
History data is now being moved to a temporary folder in the target directory.

This line ensures that there's no out of sync duplication between the history and retries tab.

By design, retries tab should only be for the current test run. And this allure-results folder should be cleared every run except for the history data, which is what we now map to.

2024-11-09 12:14 UTC, MohabMohie commented on src/main/java/com/shaft/tools/io/internal/AllureManager.java
> +            internalTerminalSession.performTerminalCommand(getCommandToCreateAllureReport(customReportName, false));
After discussion via slack your points made lots of sense and we agreed to use the following setup

allure.accumulateHistory=true
allure.accumulateReports=true
allure.cleanResultsDirectory=true

2024-11-10 20:04 UTC, AhmdZanoon approved these changes
nice and clean implementation as usual.
thanks @MohabMohie for your time and effort 😊

2024-11-10 20:04 UTC, merged