Fix Bug #960 and enhance overlay images
ShaftHQ/SHAFT_ENGINE pull request #964
Opened 2023-03-19 14:48 UTC by magdyheiba

here are the screenshots of chrome, firefox and Safari browsers
<img width="1512" alt="Screenshot 2023-03-19 at 4 43 32 PM" src="https://user-images.githubusercontent.com/38945724/226183856-c190ef0e-5bed-4274-8674-6def6999ccb8.png">
<img width="1512" alt="Screenshot 2023-03-19 at 4 42 02 PM" src="https://user-images.githubusercontent.com/38945724/226183828-d42e3a8f-9646-4f69-8970-bd6851bb8c20.png">
<img width="1512" alt="Screenshot 2023-03-19 at 4 42 49 PM" src="https://user-images.githubusercontent.com/38945724/226183845-52aabe73-18a7-4882-bd9a-14314c3f080d.png">

2023-03-21 12:22 UTC, MohabMohie commented
I don't see a watermark for the chrome screenshot. Also, please refrain from using text based browser name comparisons or creating special flows for certain browsers as this introduces inconsistency.

2023-03-21 13:43 UTC, MohabMohie requested changes
I don't see a watermark for the chrome screenshot. Also, please refrain from using text based browser name comparisons or creating special flows for certain browsers as this introduces inconsistency.

2023-03-22 08:49 UTC, magdyheiba commented
As discussed with @MahmoudElSharkawy in a call we will remove the if/else browser specific and keep it this way to fix the current issue and we will open an enhancement ticket to restructure the GIF builder.

The current issue is in the first image captured by the browser changed from browser to another in terms of dimensions so that we have different in size GIFs across all browsers as we depend on the first screenshot to build GIF.

Currently the GIF of chrome is a bit small but it was originally small as well before the bug but on Safari and firefox more than perfect 

Here is the screenshot of chrome :- 
<img width="1512" alt="Screenshot 2023-03-22 at 10 47 13 AM" src="https://user-images.githubusercontent.com/38945724/226848782-dfa53969-7476-4a8d-a8c5-8a5bdf39efd6.png">

2023-03-23 22:59 UTC, MohabMohie approved these changes

2023-03-23 22:59 UTC, merged